version: '3'

networks:
  swapi:

services:
  php7:
    container_name: swapi
    build:
      context: .
      dockerfile: ./etc/docker/dockerfile_php_7
    volumes:
      - ./../app:/var/www/html
      - ./etc/php:/usr/local/etc/php
      - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
      - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
    ports:
      - "8105:80"
    networks:
      - swapi
    depends_on:
      - mysql
  mysql:
    container_name: swapi-mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=swapi
      - MYSQL_DATABASE=swapi
    volumes:
      - ./etc/mysql:/docker-entrypoint-initdb.d
    networks:
      - swapi